-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CONCAT(CONCAT(CITY, ' '), CONCAT(STREET_ADDRESS1, ' ')), STREET_ADDRESS2) AS 전체주소, SUBSTR(TLNO, 1, 3) || '-'|| SUBSTR(TLNO, 4, 4) || '-'|| SUBSTR(TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_USER
WHERE (USER_ID, NICKNAME) IN(
    SELECT UGB.WRITER_ID, UGU.NICKNAME
    FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_USER UGU
    ON UGB.WRITER_ID = UGU.USER_ID
    GROUP BY UGB.WRITER_ID, UGU.NICKNAME
    HAVING COUNT(UGB.WRITER_ID) >= 3
)
ORDER BY USER_ID DESC

