-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME
FROM ANIMAL_OUTS AO JOIN (SELECT AI.ANIMAL_ID
FROM ANIMAL_INS AI
WHERE AI.SEX_UPON_INTAKE LIKE 'I%') TOTAL
ON AO.ANIMAL_ID = TOTAL.ANIMAL_ID
WHERE AO.SEX_UPON_OUTCOME LIKE 'N%' OR AO.SEX_UPON_OUTCOME LIKE 'S%'
ORDER BY AO.ANIMAL_ID, AO.ANIMAL_TYPE, AO.NAME