-- 코드를 입력하세요
SELECT TO_CHAR(OS.SALES_DATE, 'YYYY') AS YEAR,
TO_NUMBER(TO_CHAR(OS.SALES_DATE , 'MM')) AS MONTH,
GENDER, COUNT(DISTINCT(UI.USER_ID))
FROM USER_INFO UI JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
GROUP BY TO_CHAR(OS.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(OS.SALES_DATE , 'MM')), UI.GENDER
HAVING UI.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER