-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), COUNT(DISTINCT(UI.USER_ID)), ROUND(COUNT(DISTINCT(UI.USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021'), 1)
FROM ONLINE_SALE OS LEFT JOIN USER_INFO UI
ON OS.USER_ID = UI.USER_ID
WHERE YEAR(UI.JOINED) = '2021'
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)