-- 코드를 입력하세요
SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) AS MONTH, COUNT(DISTINCT(UI.USER_ID)) AS PUCHASED_USERS,
TO_CHAR(ROUND( 
    COUNT(DISTINCT(UI.USER_ID)) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1))  AS PUCHASED_RATIO
FROM USER_INFO UI JOIN ONLINE_SALE OS 
ON UI.USER_ID = OS.USER_ID
WHERE TO_CHAR(UI.JOINED, 'YYYY') = '2021'
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE,'MM')
ORDER BY YEAR, MONTH