-- 코드를 입력하세요

    SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME ,SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_PRICE
    FROM FOOD_PRODUCT FP, FOOD_ORDER FO
    WHERE FP.PRODUCT_ID = FO.PRODUCT_ID
    AND TO_CHAR(FO.PRODUCE_DATE, 'YYYY-MM') = '2022-05'
    GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
    ORDER BY TOTAL_PRICE DESC, FP.PRODUCT_ID ASC



