SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(A.AMOUNT) * FP.PRICE AS TOTAL_SALES
FROM (
    SELECT FO.PRODUCT_ID, SUM(FO.AMOUNT) AS AMOUNT
    FROM FOOD_ORDER FO
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
    GROUP BY FO.PRODUCT_ID
) AS A
JOIN FOOD_PRODUCT FP ON A.PRODUCT_ID = FP.PRODUCT_ID
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC
