WITH RENTAL_INFO AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE,
           DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DAYS,
          CASE
               WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
               WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
               WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
               ELSE '7일 이하'
           END AS RENTAL_DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT RENTAL_INFO.HISTORY_ID,
       IFNULL(
          ROUND((RENTAL_INFO.DAILY_FEE * (100 - DISCOUNT_PLAN.DISCOUNT_RATE) * 0.01) * RENTAL_INFO.RENTAL_DAYS, 0),
          RENTAL_INFO.DAILY_FEE * RENTAL_INFO.RENTAL_DAYS
       ) AS FEE
FROM RENTAL_INFO
LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭') DISCOUNT_PLAN 
       ON RENTAL_INFO.RENTAL_DURATION_TYPE = DISCOUNT_PLAN.DURATION_TYPE
ORDER BY FEE DESC, RENTAL_INFO.HISTORY_ID DESC;
