SELECT A.FLAVOR
FROM (
    SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS COUNT
    FROM FIRST_HALF F JOIN JULY J
    ON F.FLAVOR = J.FLAVOR
    GROUP BY F.FLAVOR
    ORDER BY COUNT DESC) A
LIMIT 3;
