-- 코드를 입력하세요
SELECT A.FLAVOR
FROM (SELECT FH.FLAVOR, (SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)) AS COUNT
FROM FIRST_HALF FH JOIN JULY J
ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY COUNT DESC) A
WHERE ROWNUM < 4