-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, A.M - SIZE_OF_COLONY AS YEAR_DEV, ID 
FROM ECOLI_DATA JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS M
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS A
ON YEAR(DIFFERENTIATION_DATE) = A.Y
ORDER BY YEAR, YEAR_DEV
